import React, { useState } from 'react';
import Header from './components/Header';
import SearchBar from './components/SearchBar';
import NutritionDisplay from './components/NutritionDisplay';
import { NutritionData, LoadingState } from './types';
import { fetchNutritionData } from './services/geminiService';
import { AlertCircle, Apple } from 'lucide-react';

const App: React.FC = () => {
  const [data, setData] = useState<NutritionData | null>(null);
  const [loadingState, setLoadingState] = useState<LoadingState>(LoadingState.IDLE);
  const [error, setError] = useState<string | null>(null);

  const handleSearch = async (query: string) => {
    setLoadingState(LoadingState.LOADING);
    setError(null);
    setData(null);

    try {
      const result = await fetchNutritionData(query);
      setData(result);
      setLoadingState(LoadingState.SUCCESS);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Something went wrong. Please try again.");
      setLoadingState(LoadingState.ERROR);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col font-sans">
      <Header />
      
      <main className="flex-grow container mx-auto px-4 py-8 sm:py-12 flex flex-col items-center">
        
        <div className="text-center mb-8 max-w-2xl">
          <h2 className="text-4xl sm:text-5xl font-extrabold text-gray-900 mb-4 tracking-tight">
            What's in your food?
          </h2>
          <p className="text-lg text-gray-600">
            Get instant calorie counts, macro breakdowns, and health insights powered by AI.
          </p>
        </div>

        <SearchBar onSearch={handleSearch} isLoading={loadingState === LoadingState.LOADING} />

        {loadingState === LoadingState.LOADING && (
          <div className="flex flex-col items-center justify-center mt-12 animate-pulse">
            <div className="h-48 w-full max-w-4xl bg-gray-200 rounded-3xl mb-4"></div>
            <div className="h-12 w-3/4 bg-gray-200 rounded-xl mb-2"></div>
            <div className="h-8 w-1/2 bg-gray-200 rounded-xl"></div>
            <p className="mt-4 text-gray-500 font-medium">Analyzing nutritional content...</p>
          </div>
        )}

        {loadingState === LoadingState.ERROR && (
          <div className="mt-8 p-6 bg-red-50 border border-red-200 rounded-2xl flex items-start gap-4 max-w-lg animate-fade-in-up">
            <AlertCircle className="h-6 w-6 text-red-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="text-red-900 font-semibold mb-1">Analysis Failed</h3>
              <p className="text-red-700">{error}</p>
            </div>
          </div>
        )}

        {loadingState === LoadingState.SUCCESS && data && (
          <NutritionDisplay data={data} />
        )}

        {loadingState === LoadingState.IDLE && (
          <div className="mt-16 grid grid-cols-1 sm:grid-cols-3 gap-8 text-center max-w-4xl opacity-50">
            <div className="flex flex-col items-center">
              <div className="bg-white p-4 rounded-full shadow-sm mb-4">
                 <span className="text-3xl">🥑</span>
              </div>
              <h3 className="font-semibold text-gray-900">Whole Foods</h3>
              <p className="text-sm text-gray-500 mt-1">Analyze fruits, vegetables, and natural ingredients.</p>
            </div>
            <div className="flex flex-col items-center">
              <div className="bg-white p-4 rounded-full shadow-sm mb-4">
                 <span className="text-3xl">🍔</span>
              </div>
              <h3 className="font-semibold text-gray-900">Restaurant Meals</h3>
              <p className="text-sm text-gray-500 mt-1">Get estimates for popular chain menu items.</p>
            </div>
            <div className="flex flex-col items-center">
              <div className="bg-white p-4 rounded-full shadow-sm mb-4">
                 <span className="text-3xl">🥤</span>
              </div>
              <h3 className="font-semibold text-gray-900">Snacks & Drinks</h3>
              <p className="text-sm text-gray-500 mt-1">Check sugar levels in your favorite treats.</p>
            </div>
          </div>
        )}
      </main>

      <footer className="bg-white border-t border-gray-200 py-8 mt-12">
        <div className="max-w-7xl mx-auto px-4 text-center text-gray-400 text-sm">
          <div className="flex items-center justify-center gap-2 mb-2">
            <Apple size={16} />
            <span className="font-semibold">NutriScan AI</span>
          </div>
          <p>Nutritional estimates are generated by AI and may not be 100% accurate. Consult a professional for dietary advice.</p>
        </div>
      </footer>
    </div>
  );
};

export default App;